[package]
name = "usbapi"
version = "0.0.1"
authors = ["Mikael Hermansson <mikael.hermansson@mykolab.com>"]
keywords = ["usb", "usbcore", "hardware"]
edition="2018"

[dependencies]
log = ""
libc=""
nix=""
mio = "0.6.16"
serde={version = '1.0', features=['derive']}
serde-hex="" 

[dev-dependencies]
signal-hook = "0.1.5"
serde_json = "1"
toml = ""
