[package]
name = "usbapi"
version = "0.0.1"
authors = ["Mikael Hermansson <mikael.hermansson@mykolab.com>"]
keywords = ["usb", "usbcore", "hardware"]
edition="2018"

[dependencies]
libc=""
nix=""
signal-hook = "0.1.5"
crate = "0.0.2"
mio = "0.6.16"
serde={version = '1.0', features=['derive']}
serde_json="1.0"
json="*"
serde-hex={git="https://github.com/forrest-marshall/serde-hex.git"}
toml="*"
